### ISSUE TITLE
Unable to add element

### ISSUE THREAD

**Issue by grabit** [forrestkirby/flipcard-element#13]
Hi,

When they are present in a page the elements are working well but it is now impossible to add a new element.

Yootheme pro v2.2.2
Joomla 3.9.20
flipcard v2.0.5 and v2.2.0beta3

**Comment by forrestkirby** [comment]
Hi grabit,

I am not able to reproduce this problem. Do you have any more details, like a JavaScript or PHP error or a site to inspect?

> flipcard v2.0.5 and v2.2.0beta3

Make sure to use only Flipcard Element 2.2.0-beta.3 with YOOtheme Pro 2.2.0 or newer.

Kind regards
Thomas

**Comment by grabit** [comment]
You’re right it is working fine now. Sorry for disturbing. Maybe a bad connection...
