### ISSUE TITLE
somewhat happened with new updates, when try insert title, content, or any field, the card is vanished!

### ISSUE THREAD

**Issue by viccyberco** [forrestkirby/flipcard-element#14]
tried re-install too, but when edit any field, the card goes invisible and even deleting what typed, dont show up again

got same bug ?

(that only happens to me on new yootheme pro installations, had some old site and its working fine)
Victor, since 2016, a happy user of your magnificient flipcard !!  
Thankyou!

**Comment by forrestkirby** [comment]
Hi Victor,

you need to add content for at least one content field of both the front and the back. Else, the content is considered *empty* and the element will not be rendered. Content fields are title, meta,content, image and icon. For the exact rule, see the [element.php](https://github.com/forrestkirby/flipcard-element/blob/master/hd-flipcard/element.php) file. This handling has been [added in version 2.1.0.-beta.1](https://github.com/forrestkirby/flipcard-element/blob/master/CHANGELOG.md#210-beta1) and is similar to the change ”Add dynamic conditions to display elements depending on a content field“ in YOOtheme Pro 2.1.0 (June 16, 2020).

Best regards
Thomas

**Comment by jotace** [comment]
Hi, forrestkirby

When use any Style in Panel under Adjusts I lose my original title and the card show, "About the Author" text. I don't know if is my template or some private configuration, could you please check?

Regards,

Jotace

**Comment by forrestkirby** [comment]
Hi Jotace,

what you describe does not seem to be related to this issue and I could not reproduce this behaviour. Please create a separate issue for that inclusing a description of how to replicate the issue. Thanks.

Best regards
Thomas
