### ISSUE TITLE
Error message -  flipcard-element

### ISSUE THREAD

**Issue by gfantoni61** [forrestkirby/flipcard-element#2]
Hi,
I have installed the add-on and I see it in the builder, but if I tri to insert it in a page I have this error.
0
Call to a member function add() on null
![See the sceenshoot](https://demo.webadvisors.it/del/del.png)
My version is:
Joomla! 3.9.14

**Comment by forrestkirby** [comment]
Looks like you are using YOOtheme Pro 2.0.0-beta which has some changes. Please try [this branch](https://github.com/forrestkirby/flipcard-element/tree/forrestkirby-patch-1). Also see #1

**Comment by gfantoni61** [comment]
Hi,
thank is perfect!!

Gianni
