### ISSUE TITLE
first image flip but cover the second when hovering

### ISSUE THREAD

**Issue by sulivieri** [forrestkirby/flipcard-element#20]
**Describe the bug**
I used a svg image in front (a logo)
a second svg image with circle around the logo
both with transparent logo (tested also with white background color)
size is setup to 150px

The problem show only on Safari:
when i hover the front image, it flip but still visibile and it cover the second image
No problem on Chrome, Opera or Firefox

**To Reproduce**
setup the module as it should be...

**Expected behavior**
flip the first image, show the second image

**Desktop (please complete the following information):**
 - Device: YooTheme Pro 2.3.30 on localmachine
 - OS:  Mac OS Catalina 10.15.7
 - Browser: Safari
 - Version: 14.0.2 (15610.3.7.1.10, 15610)

**Smartphone (please complete the following information):**
 - Device:
 - OS: 
 - Browser:
 - Version:

**Additional context**
No problem on Chrome, Opera or Firefox

**Comment by forrestkirby** [comment]
Hi sulivieri,

I could not reproduce this issue. Could you please provide me with the layout JSON and the images you used or share a link to a page where the issue can be seen? Thanks.

Kind regards
Thomas

**Comment by forrestkirby** [comment]
Closed due to inactivity
