### ISSUE TITLE
Issue with HD Flipcard in Safari, Don't show the front image

### ISSUE THREAD

**Issue by ososa** [forrestkirby/flipcard-element#26]
**Describe the bug**
The HD Flipcard don't show the front image in Safari. In Firefox/Chrome work fine!

**To Reproduce**
1. Go to 'https://cepmdev.com/'
2. Scroll down to ''
3. See error Don't show the image in Safari. In Firefox/Chrome work fine!

**Expected behavior**
Show the images like In Firefox and Chrome

**Screenshots**

**Client (please complete the following information):**
 - OS [...]
 - Browser [safari]
 - YOOtheme Pro Version [4.0.8 ]
 - Custom Element Version [...]

**Additional context**

**Comment by ososa** [comment]
![WhatsApp Image 2023-07-31 at 12 25 33 PM](https://github.com/forrestkirby/flipcard-element/assets/3370976/746aa91e-e0e9-4a80-9a39-4b1d740ce6d4)
![WhatsApp Image 2023-07-31 at 12 20 30 PM](https://github.com/forrestkirby/flipcard-element/assets/3370976/1afe319f-6fbf-49f1-a4b8-fb367a1d4bbb)

**Comment by forrestkirby** [comment]
I cannot see any flipcard the website you linked to, it only shows a “coming soon” message, and I could not replicate this issue with the demo page using Safari on macOS.

**Comment by ososa** [comment]
Hello Forrestkirby, sorry for my delay to respond. I couldn't see your reply email.

Here is the url

https://cepmdev.com/iev2/flipcard/
