### ISSUE TITLE
Vertical align of Content

### ISSUE THREAD

**Issue by channelsurfer** [forrestkirby/flipcard-element#4]
is there a way to center the back-content of the card vertically in the middle?

**Comment by forrestkirby** [comment]
This is not a feature of this element, but you could try the following:

- edit the file `/hd-flipcard/templates/template.php`
	- change line 262 `<?= $back($props) ?>` to `<?= $back($props) ?><div>`
	- change line 297 `<?= $back->end() ?>` to `</div><?= $back->end() ?>`
- edit the file `/hd-flipcard/css/flipcard.css` and add the following at the very end

```
.hd-flipcard .el-card-back > div {
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
	padding-right: 40px;
}
```

The padding might need adjustment for specific viewport sizes.
