### ISSUE TITLE
Problem with Yootheme PRO 2.0

### ISSUE THREAD

**Issue by freled** [forrestkirby/flipcard-element#6]
Hi,

When updated to yootheme pro 2.0 websites with your elements in child theme returns an error at access :
0
CALL TO A MEMBER FUNCTION ADD() ON NULL

Deletion of  your elements or unactivation of the child theme solve the problem.
Guess that you can solve this problem asap, your elements are very usefull  for some websites.
I take time to say thank you for the time you give to the community .

Regards
Frédéric

![screenshot-psychologue-delgrange fr-2020 03 12-15_47_08](https://user-images.githubusercontent.com/5160218/76533710-c3ad7780-6478-11ea-9126-db75b7ffa495.png)

**Comment by forrestkirby** [comment]
Hi Frédéric,

thank you for your kind words. Regarding the issue: The master branch has already been updated to be compatible with YOOtheme Pro 2.0 about 12 days ago. With this update, the `$app['styles']->add` function in the `element.php` has been replaced by the ` $metadata->set()` function. Please download the [latest package](https://github.com/forrestkirby/flipcard-element/archive/master.zip) and replace the files on your server with the files from this package. Clear your browser and page cache or do a hard refresh ([Ctrl+F5] or [Cmd+F5]) when you have opened the page builder. The error should be gone. If you are using further custom elements, make sure that those are up to date as well.

Regards
Thomas

**Comment by freled** [comment]
Sorry for my absolute lack of attention on the fact that the packages have been updated. Thanks à lot for your kick answer. 




Téléchargez Outlook pour Android






On Thu, Mar 12, 2020 at 10:06 PM +0100, "forrestkirby" <notifications@github.com> wrote:
















Hi Frédéric,



thank you for your kind words. Regarding the issue: The master branch has already been updated to be compatible with YOOtheme Pro 2.0 about 12 days ago. With this update, the $app['styles']->add function in the element.php has been replaced by the  $metadata->set() function. Please download the latest package and replace the files on your server with the files from this package. Clear your browser and page cache or do a hard refresh ([Ctrl+F5] or [Cmd+F5]) when you have opened the page builder. The error should be gone. If you are using further custom elements, make sure that those are up to date as well.



Regards


Thomas
