### ISSUE TITLE
Take count of the back card size

### ISSUE THREAD

**Issue by grabit** [forrestkirby/flipcard-element#8]
Hello,

I have seen that this "issue" was already in the todo list but when do you plan to add it because we think this is an important problem.

This is more obvious when the size of the screen reduces with simple front cards (image and title) and a text at the back. The image is resized the title takes a bit more room but at the back the text takes a lot more place even if at original screen size it fits perfectly.

**Comment by forrestkirby** [comment]
Hi grabit,

could you please test #9?

Regards
Thomas
